In [1]:
!pip3 install pickle5
import pickle5 as pickle
import pandas as pd

You should consider upgrading via the 'C:\Users\nickh\anaconda3\envs\cm2\python.exe -m pip install --upgrade pip' command.


In [2]:
def load_pickle_file(fname):
    try:
        data = pd.read_pickle(fname)
    except:
        with open(fname, "rb") as fh:
            data = pickle.load(fh)
            data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
    return data

In [10]:
# iemocap1 = load_pickle_file('iemocap_session1_af.pickle')
# iemocap2 = load_pickle_file('iemocap_session2_af.pickle')
# iemocap3 = load_pickle_file('iemocap_session3_af.pickle')
# iemocap4 = load_pickle_file('iemocap_session4_af.pickle')
# iemocap5 = load_pickle_file('iemocap_session5_af.pickle')

iemocap1 = pd.read_csv('iemocap_session1_af.csv')
iemocap1 = iemocap1.loc[:, ~iemocap1.columns.str.contains('^Unnamed')]
iemocap2 = pd.read_csv('iemocap_session2_af.csv')
iemocap2 = iemocap2.loc[:, ~iemocap2.columns.str.contains('^Unnamed')]
iemocap3 = pd.read_csv('iemocap_session3_af.csv')
iemocap3 = iemocap3.loc[:, ~iemocap3.columns.str.contains('^Unnamed')]
iemocap4 = pd.read_csv('iemocap_session4_af.csv')
iemocap4 = iemocap4.loc[:, ~iemocap4.columns.str.contains('^Unnamed')]
iemocap5 = pd.read_csv('iemocap_session5_af.csv')
iemocap5 = iemocap5.loc[:, ~iemocap5.columns.str.contains('^Unnamed')]

In [11]:
print(len(iemocap1))
print(len(iemocap2))
print(len(iemocap3))
print(len(iemocap4))
print(len(iemocap5))
len(iemocap1) + len(iemocap2) + len(iemocap3) + len(iemocap4) + len(iemocap5)

1819
1762
1760
1865
2170


9376

In [12]:
acoustic_feature_columns = [c for c in iemocap1.columns][5:]

In [13]:
iemocap1

TURN  \
0        Ses01F_impro01_F000   
1        Ses01F_impro01_M000   
2        Ses01F_impro01_F001   
3        Ses01F_impro01_M001   
4        Ses01F_impro01_F002   
...                      ...   
1814  Ses01M_script03_2_F040   
1815  Ses01M_script03_2_M041   
1816  Ses01M_script03_2_F041   
1817  Ses01M_script03_2_M042   
1818  Ses01M_script03_2_M043   

                                              UTTERANCE   DA EMOTION  \
0                                            Excuse me.    c     neu   
1                               Do you have your forms?    q     fru   
2                                                 Yeah.  ans     neu   
3                                      Let me see them.    s     fru   
4                                   Is there a problem?    q     neu   
...                                                 ...  ...     ...   
1814  This is the end do you hear me?  Finally and f...    s     ang   
1815                        You're not going like this.    c     ang   
1816  Oh yes I am...Oh yes I am. Let go of me. You l...    o     ang   
1817                                     No you're not.  dag     ang   
1818  Shut up. Shut up. I wouldn't marry you again i...    o     ang   

                  audio_file  F0semitoneFrom27.5Hz_sma3nz_amean_b  \
0        Ses01F_impro01_F000                             0.000000   
1        Ses01F_impro01_M000                             0.000000   
2        Ses01F_impro01_F001                             0.000000   
3        Ses01F_impro01_M001                            26.122112   
4        Ses01F_impro01_F002                             0.000000   
...                      ...                                  ...   
1814  Ses01M_script03_2_F040                            32.384240   
1815  Ses01M_script03_2_M041                             0.000000   
1816  Ses01M_script03_2_F041                            40.590290   
1817  Ses01M_script03_2_M042                            31.108418   
1818  Ses01M_script03_2_M043                            46.032696   

      F0semitoneFrom27.5Hz_sma3nz_stddevNorm_b  \
0                                     0.000000   
1                                     0.000000   
2                                     0.000000   
3                                     0.032891   
4                                     0.000000   
...                                        ...   
1814                                  0.081119   
1815                                  0.000000   
1816                                  0.169796   
1817                                  0.012443   
1818                                  0.099883   

      F0semitoneFrom27.5Hz_sma3nz_percentile20.0_b  \
0                                         0.000000   
1                                         0.000000   
2                                         0.000000   
3                                        26.099644   
4                                         0.000000   
...                                            ...   
1814                                     30.534610   
1815                                      0.000000   
1816                                     34.144410   
1817                                     30.754486   
1818                                     43.077580   

      F0semitoneFrom27.5Hz_sma3nz_percentile50.0_b  \
0                                         0.000000   
1                                         0.000000   
2                                         0.000000   
3                                        26.244362   
4                                         0.000000   
...                                            ...   
1814                                     31.911644   
1815                                      0.000000   
1816                                     40.024890   
1817                                     30.995090   
1818                                     45.162704   

      F0semitoneFrom27.5Hz_sma3nz_percentile80

In [14]:
# Get the DA labels
da_labels_iemocap1 = iemocap1['DA']
da_labels_iemocap2 = iemocap2['DA']
da_labels_iemocap3 = iemocap3['DA']
da_labels_iemocap4 = iemocap4['DA']
da_labels_iemocap5 = iemocap5['DA']

# Emotion labels
emot_labels_iemocap1 = iemocap1['EMOTION']
emot_labels_iemocap2 = iemocap2['EMOTION']
emot_labels_iemocap3 = iemocap3['EMOTION']
emot_labels_iemocap4 = iemocap4['EMOTION']
emot_labels_iemocap5 = iemocap5['EMOTION']

In [15]:
# Get a sense of the value counts for the data
full_da_labels = pd.concat([da_labels_iemocap1, da_labels_iemocap2, da_labels_iemocap3, da_labels_iemocap4, da_labels_iemocap5])
full_da_labels.value_counts()

s      2170
o      2073
q      1945
ans    1429
ag      497
dag     372
c       350
b       284
ap       75
oth      68
g        59
a        54
Name: DA, dtype: int64

In [16]:
full_emot_data = pd.concat([emot_labels_iemocap1, emot_labels_iemocap2, emot_labels_iemocap3, emot_labels_iemocap4, emot_labels_iemocap5])
full_emot_data.value_counts()

xxx    2305
fru    1714
neu    1613
ang    1034
sad    1011
exc     999
hap     563
sur      94
fea      38
oth       3
dis       2
Name: EMOTION, dtype: int64

In [17]:
# Turn code into categorical data
# Create one hot embeddings of the label values (0, 1, 2)
from tensorflow.keras.utils import to_categorical
from sklearn import preprocessing
import numpy as np

# Full set of dialogue act labels
da_labels = ['s', 'q', 'o', 'ans', 'c', 'ag', 'b', 'dag', 'oth', 'a', 'ap', 'g']
da_encoder = preprocessing.LabelEncoder()
da_encoder.fit(da_labels)

emotion_labels = ['xxx', 'fru', 'neu', 'ang', 'sad', 'exc', 'hap', 'sur', 'fea', 'oth', 'dis']
emotion_encoder = preprocessing.LabelEncoder()
emotion_encoder.fit(emotion_labels)

def convert_da_labels_to_categorical(dialog_acts):
    num_labels = da_encoder.transform(dialog_acts)
    cat_labels = to_categorical(num_labels)
    return cat_labels

def convert_cat_da_to_string(cat_das):
    num_labels = np.argmax(cat_das, axis=-1)
    return da_encoder.inverse_transform(num_labels)

def convert_emot_labels_to_categorical(emot_data):
    num_labels = emotion_encoder.transform(emot_data)
    cat_labels = to_categorical(num_labels)
    return cat_labels

def convert_cat_emot_to_string(cat_emot_data):
    num_labels = np.argmax(cat_emot_data, axis=-1)
    return emotion_encoder.inverse_transform(num_labels)

In [18]:
print(da_labels_iemocap1[0])
cat_1_labels = convert_da_labels_to_categorical(da_labels_iemocap1)
print(cat_1_labels[0])
string_das = convert_cat_da_to_string(cat_1_labels)
print(string_das[0])

print(emot_labels_iemocap1[0])
cat_1_emot_labels = convert_emot_labels_to_categorical(emot_labels_iemocap1)
print(cat_1_emot_labels[0])
string_emot = convert_cat_emot_to_string(cat_1_emot_labels)
print(string_emot[0])

c
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
c
neu
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
neu


In [19]:
X = iemocap2[acoustic_feature_columns].to_numpy()
y_da = convert_da_labels_to_categorical(iemocap2['DA'])
y_emot = convert_emot_labels_to_categorical(iemocap2['EMOTION'])

In [44]:
from keras import layers, Input, Model, Sequential
from tensorflow.python.keras.layers.core import Dropout
from tensorflow.keras.callbacks import EarlyStopping

def build_and_train_model(X, y_da):
    callback = EarlyStopping(monitor='loss', patience=5)
    model = Sequential()
    model.add(layers.Dense(512, input_dim=X.shape[1], activation='relu'))
    model.add(Dropout(0.1))
    model.add(layers.Dense(256, activation='relu'))
    model.add(Dropout(0.1))
    model.add(layers.Dense(128, activation='relu'))
    model.add(layers.Dense(len(y_da[0]), activation="softmax"))
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    history = model.fit(X, y_da, batch_size=32, epochs=100, validation_split=0.2, callbacks=[callback])
    return (model, history)

In [45]:
build_and_train_model(X, y_da)

Epoch 1/100
189/189 [==============================] - 1s 2ms/step - loss: 30.0153 - accuracy: 0.1881 - val_loss: 2.1816 - val_accuracy: 0.2348
Epoch 2/100
189/189 [==============================] - 0s 2ms/step - loss: 2.3865 - accuracy: 0.2308 - val_loss: 3.0760 - val_accuracy: 0.2057
Epoch 3/100
189/189 [==============================] - 0s 2ms/step - loss: 2.1363 - accuracy: 0.2256 - val_loss: 3.9581 - val_accuracy: 0.2123
Epoch 4/100
189/189 [==============================] - 0s 2ms/step - loss: 2.1506 - accuracy: 0.2339 - val_loss: 11.5373 - val_accuracy: 0.2057
Epoch 5/100
189/189 [==============================] - 0s 2ms/step - loss: 1.9942 - accuracy: 0.2356 - val_loss: 15.8801 - val_accuracy: 0.2169
Epoch 6/100
189/189 [==============================] - 0s 2ms/step - loss: 1.9776 - accuracy: 0.2380 - val_loss: 8.6488 - val_accuracy: 0.2050
Epoch 7/100
189/189 [==============================] - 0s 2ms/step - loss: 1.9669 - accuracy: 0.2387 - val_loss: 7.9871 - val_accuracy: 0.2

(<keras.engine.sequential.Sequential at 0x2af8fa108c8>,
 <keras.callbacks.History at 0x2af8fa4b508>)

In [83]:
preds = model1.predict(X)

#preds = [np.argmax(pred) for pred in preds]
#pd.DataFrame(data=np.array(preds)).value_counts()

np.argmax(preds, axis=-1)

array([6, 8, 6, ..., 0, 2, 2], dtype=int64)

In [24]:
X.shape

(1762, 264)

In [27]:
# create train/test fold assignments

tr1 = pd.concat([iemocap1, iemocap2, iemocap3, iemocap4])
te1 = iemocap5

tr2 = pd.concat([iemocap1, iemocap2, iemocap3, iemocap5])
te2 = iemocap4

tr3 = pd.concat([iemocap1, iemocap2, iemocap4, iemocap5])
te3 = iemocap3

tr4 = pd.concat([iemocap1, iemocap3, iemocap4, iemocap5])
te4 = iemocap2

tr5 = pd.concat([iemocap2, iemocap3, iemocap4, iemocap5])
te5 = iemocap1

splits = [(tr1, te1), (tr2, te2), (tr3, te3), (tr4, te4), (tr5, te5)]

In [46]:
for s in splits:
    tr, te = s
    X_train = tr[acoustic_feature_columns].to_numpy()
    y_train = convert_da_labels_to_categorical(tr['DA'])
    X_test = te[acoustic_feature_columns].to_numpy()
    y_test = convert_da_labels_to_categorical(te['DA'])
    model, history = build_and_train_model(X_train, y_train)
    
    preds = model.predict(X_test)

Epoch 1/100
181/181 [==============================] - 1s 2ms/step - loss: 28.0595 - accuracy: 0.1860 - val_loss: 2.2715 - val_accuracy: 0.2233
Epoch 2/100
181/181 [==============================] - 0s 2ms/step - loss: 2.3062 - accuracy: 0.2292 - val_loss: 2.2231 - val_accuracy: 0.2517
Epoch 3/100
181/181 [==============================] - 0s 2ms/step - loss: 2.1170 - accuracy: 0.2248 - val_loss: 2.1294 - val_accuracy: 0.2254
Epoch 4/100
181/181 [==============================] - 0s 2ms/step - loss: 2.0610 - accuracy: 0.2273 - val_loss: 2.1269 - val_accuracy: 0.2524
Epoch 5/100
181/181 [==============================] - 0s 2ms/step - loss: 2.0299 - accuracy: 0.2292 - val_loss: 2.0684 - val_accuracy: 0.2566
Epoch 6/100
181/181 [==============================] - 0s 2ms/step - loss: 2.0077 - accuracy: 0.2368 - val_loss: 2.1209 - val_accuracy: 0.2601
Epoch 7/100
181/181 [==============================] - 0s 2ms/step - loss: 2.0444 - accuracy: 0.2299 - val_loss: 2.1122 - val_accuracy: 0.261

191/191 [==============================] - 0s 2ms/step - loss: 1.9266 - accuracy: 0.2502 - val_loss: 1.9501 - val_accuracy: 0.2277
Epoch 21/100
191/191 [==============================] - 0s 2ms/step - loss: 1.9191 - accuracy: 0.2564 - val_loss: 1.9527 - val_accuracy: 0.2684
Epoch 22/100
191/191 [==============================] - 0s 2ms/step - loss: 1.9420 - accuracy: 0.2556 - val_loss: 1.8726 - val_accuracy: 0.2644
Epoch 23/100
191/191 [==============================] - 0s 2ms/step - loss: 1.9386 - accuracy: 0.2487 - val_loss: 2.1311 - val_accuracy: 0.2257
Epoch 24/100
191/191 [==============================] - 0s 2ms/step - loss: 1.9215 - accuracy: 0.2421 - val_loss: 2.1035 - val_accuracy: 0.2539
Epoch 25/100
191/191 [==============================] - 0s 2ms/step - loss: 1.9259 - accuracy: 0.2533 - val_loss: 2.0382 - val_accuracy: 0.2480
Epoch 26/100
191/191 [==============================] - 0s 2ms/step - loss: 1.9117 - accuracy: 0.2598 - val_loss: 2.0839 - val_accuracy: 0.2362
Epoch

In [47]:
preds

array([[0.00441032, 0.05804019, 0.14751689, ..., 0.00506384, 0.18958172,
        0.25365913],
       [0.00441032, 0.05804019, 0.14751689, ..., 0.00506384, 0.18958172,
        0.25365913],
       [0.00441032, 0.05804019, 0.14751689, ..., 0.00506384, 0.18958172,
        0.25365913],
       ...,
       [0.00441032, 0.05804019, 0.1475169 , ..., 0.00506384, 0.18958174,
        0.2536591 ],
       [0.00441032, 0.05804019, 0.1475169 , ..., 0.00506384, 0.18958174,
        0.2536591 ],
       [0.00441032, 0.05804019, 0.1475169 , ..., 0.00506384, 0.18958174,
        0.2536591 ]], dtype=float32)